%hidden MODULE_NAME="ctp_datetime"

set -ogq "@catppuccin_${MODULE_NAME}_icon" '󰭦 '
set -ogq "@catppuccin_${MODULE_NAME}_color" '#{l:#{cpu_bg_color}}'
set -ogq "@catppuccin_${MODULE_NAME}_text" ' %Y-%m-%d 󰅐 %H:%M:%S'

source -F '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/utils/status_module.conf'

